### ISSUE TITLE
Doesn't seem to work if projects are purely 'npm' with no bower.json

### ISSUE THREAD

**Issue by robross0606** [davidrleonard/dep-index#3]
If configured like this:
```
depIndex({
    packageManagers: ['npm']
  })
```
Even tho it detects the right number of projects and each one has a `package.json` file, attempts to `search()` or `crawl()` return `false` instead of a map.

**Comment by robross0606** [comment]
This also seems to assume that all things being scraped would be inside a git repo.  This isn't documented and not necessarily always true.
```
Fatal Error: fatal: not a git repository (or any of the parent directories): .git

    at C:\Code\gitops\ncp-dependency-graph\node_modules\dep-index\lib\util.js:62:37
    at C:\Code\gitops\ncp-dependency-graph\node_modules\shelljs\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:326:5)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.onexit (internal/child_process.js:288:5)
    at Process.callbackTrampoline (internal/async_hooks.js:134:14)
```
